# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: ubuntu-latest
    steps:
    
    - task: Docker@2
      displayName: Login to Dockerhub
      inputs:
        command: login
        containerRegistry: dockerhub
    
    - task: Docker@2
      displayName: Build an image
      inputs:
        command: buildAndPush
        dockerfile: '$(Build.SourcesDirectory)/dockerfile'
        containerRegistry: 'dockerhub'
        repository: 'appservicesample'
        tags: |
          $(tag)
    
    - task: Docker@2
      displayName: Logout 
      inputs:
        command: logout
        containerRegistry: dockerhub